# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Clark Richards
tagline:          "Coded Ocean"
description:      "Ramblings about oceanography, coding, R, and other stuff"
url:              
baseurl:          http://richardsc.github.io/

author:
  name:           'Clark Richards'
  url:            https://twitter.com/clarkgrichards

paginate:         5

# Custom vars
version:          2.1.0

github:
  home:	          https://github.com/richardsc/
  repo:           https://github.com/richardsc/richardsc.github.io
