# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Clark Richards, PhD"
tagline:          "Coded Ocean"
description:      "Oceanographer, father, musician, cyclist. Co-author of the Rstats oce package for ocean data analysis."
url:              
baseurl:          http://richardsc.github.io/

author:
  name:           'Clark Richards'
  url:            https://twitter.com/clarkgrichards

paginate:         5

# Custom vars
version:          2.1.0

# set limit on number of post to appear on Home page
homepostlimit: 4

# Social Media
twitter:          true # add a twitter button to each post
facebook:         true # add a facebook share button to each post


github:
  home:	          https://github.com/richardsc/
  repo:           https://github.com/richardsc/richardsc.github.io
